// AUTO-GENERATED by generate_tf.py — DO NOT EDIT

locals {
  playlist_tracks = [
    # Dil Ibaadat - Pritam
    "3Kl8p2PxVf8eAayLwTxOIm",
    # Zara Sa - Lofi Flip - KSW
    "4uZnwiu2fnfTKWn8zt6XZx",
    # Tadap Tadap - KK
    "6n6hEYHXBzWfdSzBX20ZRw",
    # Aankhon Mein Teri (Remix) - KK
    "27SAeCms6XAVJMcki0GpPV",
    # Khuda Jaane - Vishal-Shekhar
    "0gPgdRfB4jdGrlyXS0Vx78",
    # Yaaron - KK
    "0zFG3RWjka7dNRIRTWnXMN",
    # Maine Dil Se Kaha - KK
    "0dZjWF8uklfNUHiPS2vC6E",
    # Such Keh Raha Hai - KK
    "0ypgFw67lNEpoKFUxUV0tG",
    # Tu Aashiqui Hai - Vishal-Shekhar
    "2vuhZrEHS25D8xNQTSvuuj",
    # O Meri Jaan - KK
    "2xPgLSozcGeM6rQi5eIWmY",
    # Labon Ko - Pritam
    "5WncH5iZ5GFlnXm7jKEXVP",
    # Alvida - KALAM INK
    "0MzimbGlnX7GS2lRuD5eTT",
    # Piya Aaye Na - Tulsi Kumar
    "1ELMyeJLDHUz3cK3XTWgEi",
    # Hai Junoon - Pritam
    "5u4q3iqZ9IMbXaR7bsGYbW",
    # It's the Time to Disco - Shankar-Ehsaan-Loy
    "3hCUkos0NxuSFl73oOHJzb",
    # Happy - Pancho Beats
    "7d1Nv6JhNVSrUKwCX8PYym",
    # Walking On Sunshine - Katrina & The Waves
    "05wIrZSwuaVWhcv5FfqeH0",
    # Don't Stop Me Now - Queen
    "0DrDcqWpokMlhKYJSwoT4B",
    # September - Earth, Wind & Fire
    "2grjqo0Frpf2okIBiifQKs",
    # Uptown Funk - Mark Ronson
    "4rmFRTmHa2bWUmMLIRVEXQ",
    # Good as Hell - Lizzo
    "6KgBpzTuTRPebChN0VTyzV",
    # I Want You Back - The Jackson 5
    "5LxvwujISqiB8vpRYv887S",
    # Dancing Queen - ABBA
    "0GjEhVFGZW8afUYGChu3Rr",
    # Hey Ya! - Outkast
    "2PpruBYCo4H7WOBJ7Q2EwM",
    # CAN'T STOP THE FEELING! - Film Version - Justin Timberlake
    "4sQmCQUZcnBPaVm4dEUKv7",
    # Shake It Off - Taylor Swift
    "0cqRj7pUJDkTCEsJkx8snD",
    # Dynamite - BTS
    "72IwoG8tqvIWV10IHjpNNA",
    # Sugar - Maroon 5
    "5d6Mjuu2uCGRPYpFjGpCX5",
    # Treasure - Bruno Mars
    "55h7vJchibLdUkxdlX3fK7",
    # Rude - MAGIC!
    "6RtPijgfPKROxEzTHNRiDp",
  ]
}
